"""
Curated database of pharmaceutical active ingredients commonly encapsulated in polymeric nanoparticles.
Includes clinical and preclinical drugs across oncology, anti-inflammatory, antimicrobial, and natural products.
"""

CURATED_DRUG_DATABASE = {
    "Paclitaxel": {
        "name": "Paclitaxel",
        "category": "Antineoplastic / Taxane",
        "smiles": "CC1=C2[C@@H](C(=O)C3(C(C[C@@H]4[C@](C3=O)([C@@H]([C@@H]5[C@]4(C[C@@H](C(=C5C)C)OC(=O)C)OC(=O)C)OC(=O)c6ccccc6)O)O)C)C(=O)[C@@H]1OC(=O)[C@H](O)[C@@H](NC(=O)c7ccccc7)c8ccccc8",
        "mol_MW": 853.92,
        "mol_logP": 3.74,
        "mol_TPSA": 221.29,
        "mol_melting_point": 216.0,
        "mol_Hacceptors": 14,
        "mol_Hdonors": 4,
        "mol_heteroatoms": 15,
        "therapeutic_class": "Anticancer (Microtubule Stabilizer)",
        "clinical_stage": "FDA Approved (Taxol, Abraxane)"
    },
    "Docetaxel": {
        "name": "Docetaxel",
        "category": "Antineoplastic / Taxane",
        "smiles": "CC1=C2[C@@H](C(=O)C3(C(C[C@@H]4[C@](C3=O)([C@@H]([C@@H]5[C@]4(C[C@@H](C(=C5C)C)OC(=O)C)O)OC(=O)c6ccccc6)O)O)C)C(=O)[C@@H]1OC(=O)[C@H](O)[C@@H](NC(=O)OC(C)(C)C)c7ccccc7",
        "mol_MW": 807.89,
        "mol_logP": 3.26,
        "mol_TPSA": 224.45,
        "mol_melting_point": 232.0,
        "mol_Hacceptors": 14,
        "mol_Hdonors": 5,
        "mol_heteroatoms": 15,
        "therapeutic_class": "Anticancer (Microtubule Stabilizer)",
        "clinical_stage": "FDA Approved"
    },
    "Doxorubicin": {
        "name": "Doxorubicin",
        "category": "Anthracycline Chemotherapeutic",
        "smiles": "CC1C(C(CC(O1)OC2CC(CC3=C2C(=O)C4=C(C3=O)C(=CC=C4)OC)(C(=O)CO)O)N)O",
        "mol_MW": 543.52,
        "mol_logP": 1.27,
        "mol_TPSA": 206.07,
        "mol_melting_point": 229.0,
        "mol_Hacceptors": 12,
        "mol_Hdonors": 6,
        "mol_heteroatoms": 13,
        "therapeutic_class": "Anticancer (DNA Intercalator / Topo II)",
        "clinical_stage": "FDA Approved (Doxil, Myocet)"
    },
    "Curcumin": {
        "name": "Curcumin",
        "category": "Polyphenol / Phytochemical",
        "smiles": "COC1=C(C=CC(=C1)/C=C/C(=O)CC(=O)/C=C/C2=CC(=C(C=C2)O)OC)O",
        "mol_MW": 368.38,
        "mol_logP": 3.20,
        "mol_TPSA": 93.06,
        "mol_melting_point": 183.0,
        "mol_Hacceptors": 6,
        "mol_Hdonors": 2,
        "mol_heteroatoms": 6,
        "therapeutic_class": "Anti-inflammatory / Antioxidant",
        "clinical_stage": "Clinical Trials (Phase II/III)"
    },
    "Dexamethasone": {
        "name": "Dexamethasone",
        "category": "Glucocorticoid Anti-inflammatory",
        "smiles": "CC1CC2C3CCC4=CC(=O)C=CC4(C3(C(CC2(C1(C(=O)CO)O)C)O)F)C",
        "mol_MW": 392.46,
        "mol_logP": 1.83,
        "mol_TPSA": 94.83,
        "mol_melting_point": 262.0,
        "mol_Hacceptors": 5,
        "mol_Hdonors": 3,
        "mol_heteroatoms": 6,
        "therapeutic_class": "Corticosteroid",
        "clinical_stage": "FDA Approved (Ozurdex)"
    },
    "Methotrexate": {
        "name": "Methotrexate",
        "category": "Antifolate Antineoplastic",
        "smiles": "CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C(=O)NC(CCC(=O)O)C(=O)O",
        "mol_MW": 454.44,
        "mol_logP": -1.85,
        "mol_TPSA": 210.53,
        "mol_melting_point": 195.0,
        "mol_Hacceptors": 12,
        "mol_Hdonors": 5,
        "mol_heteroatoms": 13,
        "therapeutic_class": "Antineoplastic / Immunosuppressant",
        "clinical_stage": "FDA Approved"
    },
    "Diclofenac": {
        "name": "Diclofenac",
        "category": "NSAID",
        "smiles": "C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl",
        "mol_MW": 296.15,
        "mol_logP": 4.51,
        "mol_TPSA": 49.33,
        "mol_melting_point": 156.0,
        "mol_Hacceptors": 2,
        "mol_Hdonors": 2,
        "mol_heteroatoms": 5,
        "therapeutic_class": "Analgesic / Anti-inflammatory",
        "clinical_stage": "FDA Approved"
    },
    "Ibuprofen": {
        "name": "Ibuprofen",
        "category": "NSAID",
        "smiles": "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O",
        "mol_MW": 206.28,
        "mol_logP": 3.50,
        "mol_TPSA": 37.30,
        "mol_melting_point": 76.0,
        "mol_Hacceptors": 1,
        "mol_Hdonors": 1,
        "mol_heteroatoms": 2,
        "therapeutic_class": "NSAID / Analgesic",
        "clinical_stage": "FDA Approved"
    },
    "Quercetin": {
        "name": "Quercetin",
        "category": "Flavonoid / Antioxidant",
        "smiles": "C1=CC(=C(C=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O)O)O",
        "mol_MW": 302.24,
        "mol_logP": 1.54,
        "mol_TPSA": 127.45,
        "mol_melting_point": 316.0,
        "mol_Hacceptors": 7,
        "mol_Hdonors": 5,
        "mol_heteroatoms": 7,
        "therapeutic_class": "Cardioprotective / Chemopreventive",
        "clinical_stage": "Nutraceutical / Preclinical"
    },
    "Resveratrol": {
        "name": "Resveratrol",
        "category": "Stilbenoid Polyphenol",
        "smiles": "C1=CC(=CC=C1/C=C/C2=CC(=CC(=C2)O)O)O",
        "mol_MW": 228.24,
        "mol_logP": 3.10,
        "mol_TPSA": 60.69,
        "mol_melting_point": 261.0,
        "mol_Hacceptors": 3,
        "mol_Hdonors": 3,
        "mol_heteroatoms": 3,
        "therapeutic_class": "Anti-aging / Anti-inflammatory",
        "clinical_stage": "Nutraceutical / Clinical Trials"
    },
    "Cisplatin": {
        "name": "Cisplatin",
        "category": "Platinum Coordination Complex",
        "smiles": "N.N.[Cl-].[Cl-].[Pt+2]",
        "mol_MW": 300.05,
        "mol_logP": -2.19,
        "mol_TPSA": 52.04,
        "mol_melting_point": 270.0,
        "mol_Hacceptors": 2,
        "mol_Hdonors": 4,
        "mol_heteroatoms": 5,
        "therapeutic_class": "Antineoplastic (DNA Crosslinker)",
        "clinical_stage": "FDA Approved"
    },
    "Tamoxifen": {
        "name": "Tamoxifen",
        "category": "Selective Estrogen Receptor Modulator (SERM)",
        "smiles": "CCC(=C(C1=CC=CC=C1)C2=CC=C(C=C2)OCCN(C)C)C3=CC=CC=C3",
        "mol_MW": 371.51,
        "mol_logP": 6.30,
        "mol_TPSA": 12.47,
        "mol_melting_point": 97.0,
        "mol_Hacceptors": 2,
        "mol_Hdonors": 0,
        "mol_heteroatoms": 2,
        "therapeutic_class": "Hormone-dependent Breast Cancer",
        "clinical_stage": "FDA Approved"
    },
    "Cannabidiol": {
        "name": "Cannabidiol (CBD)",
        "category": "Cannabinoid",
        "smiles": "CCCCCC1=CC(=C(C(=C1)O)C2C=C(CCC2C(=C)C)C)O",
        "mol_MW": 314.46,
        "mol_logP": 6.33,
        "mol_TPSA": 40.46,
        "mol_melting_point": 66.0,
        "mol_Hacceptors": 2,
        "mol_Hdonors": 2,
        "mol_heteroatoms": 2,
        "therapeutic_class": "Neuroprotective / Anticonvulsant",
        "clinical_stage": "FDA Approved (Epidiolex)"
    },
    "5-Fluorouracil": {
        "name": "5-Fluorouracil (5-FU)",
        "category": "Pyrimidine Analog / Antimetabolite",
        "smiles": "C1=C(C(=O)NC(=O)N1)F",
        "mol_MW": 130.08,
        "mol_logP": -0.89,
        "mol_TPSA": 58.20,
        "mol_melting_point": 282.0,
        "mol_Hacceptors": 3,
        "mol_Hdonors": 2,
        "mol_heteroatoms": 4,
        "therapeutic_class": "Anticancer (Thymidylate Synthase Inhibitor)",
        "clinical_stage": "FDA Approved"
    },
    "Rapamycin": {
        "name": "Rapamycin (Sirolimus)",
        "category": "Macrolide / mTOR Inhibitor",
        "smiles": "CC1CCC2CC(=O)C(CC(OC(=O)C3CCCCN3C(=O)C(=O)C1(O2)O)C(C)CC4CCC(C(C4)OC)O)OC",
        "mol_MW": 914.17,
        "mol_logP": 4.30,
        "mol_TPSA": 195.00,
        "mol_melting_point": 183.0,
        "mol_Hacceptors": 13,
        "mol_Hdonors": 3,
        "mol_heteroatoms": 14,
        "therapeutic_class": "Immunosuppressant / Antineoplastic",
        "clinical_stage": "FDA Approved (Rapamune)"
    },
    "Amphotericin B": {
        "name": "Amphotericin B",
        "category": "Polyene Antifungal",
        "smiles": "CC1C=CC=CC=CC=CC=CC=CC=CC(CC2C(C(CC(O2)(CC(CC(CC(CC(CC(CC(=O)OC(C(C1O)C)C)O)O)O)O)O)O)O)O)C(=O)O)OC3C(C(C(C(O3)C)O)N)O",
        "mol_MW": 924.08,
        "mol_logP": -0.67,
        "mol_TPSA": 321.43,
        "mol_melting_point": 170.0,
        "mol_Hacceptors": 18,
        "mol_Hdonors": 12,
        "mol_heteroatoms": 18,
        "therapeutic_class": "Antifungal",
        "clinical_stage": "FDA Approved (AmBisome)"
    },
    "Ciprofloxacin": {
        "name": "Ciprofloxacin",
        "category": "Fluoroquinolone Antibiotic",
        "smiles": "C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O",
        "mol_MW": 331.34,
        "mol_logP": 0.28,
        "mol_TPSA": 74.57,
        "mol_melting_point": 255.0,
        "mol_Hacceptors": 5,
        "mol_Hdonors": 2,
        "mol_heteroatoms": 6,
        "therapeutic_class": "Broad-spectrum Antibiotic",
        "clinical_stage": "FDA Approved"
    }
}

def get_drug_names():
    return sorted(list(CURATED_DRUG_DATABASE.keys()))

def get_drug_by_name(name):
    return CURATED_DRUG_DATABASE.get(name)
